import pytest

from src.app.model.account.service.update_subjects_domain_service import UpdateSubjectsDomainService


def test_profile_success():...
def test_profile_invalid_display_name_failure():...
def test_profile_invalid_email_failure():...
def test_profile_invalid_country_failure():...


def test_basic_settings_success():...
def test_basic_settings_invalid_is_public_failure():...


def test_auth_settings_success():...
def test_auth_invalid_hashed_password_success():...