"""initial tables

Revision ID: e8d509bf2042
Revises: 
Create Date: 2026-05-16 16:17:56.318383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e8d509bf2042'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'SUSPENDED', name='accountstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    sa.UniqueConstraint('principal_id')
    )
    op.create_index(op.f('ix_account_status'), 'account', ['status'], unique=False)
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapter_id')
    )
    op.create_table('textbook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'PUBLISHED', 'ARCHIVED', name='textbookstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id')
    )
    op.create_table('account_base_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['account.principal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id')
    )
    op.create_table('account_identity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('provider', sa.Enum('FIREBASE', name='allowedidentityprovider'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['account.principal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_account_identity_provider_subject')
    )
    op.create_table('account_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['account.principal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id')
    )
    op.create_index(op.f('ix_account_metadata_deleted_at'), 'account_metadata', ['deleted_at'], unique=False)
    op.create_table('account_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sa.Enum('NOT_SET', 'JP', 'US', name='country'), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['account.principal_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal_id')
    )
    op.create_table('textbook_author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['principal_id'], ['account.principal_id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.textbook_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id', 'principal_id', name='uq_textbook_author')
    )
    op.create_index(op.f('ix_textbook_author_principal_id'), 'textbook_author', ['principal_id'], unique=False)
    op.create_table('textbook_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.chapter_id'], ),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.textbook_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id', 'chapter_id', name='uq_textbook_chapter')
    )
    op.create_index(op.f('ix_textbook_chapter_textbook_id'), 'textbook_chapter', ['textbook_id'], unique=False)
    op.create_table('textbook_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.textbook_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id')
    )
    op.create_table('textbook_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('textbook_id', sa.Uuid(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['textbook_id'], ['textbook.textbook_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('textbook_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('textbook_settings')
    op.drop_table('textbook_metadata')
    op.drop_index(op.f('ix_textbook_chapter_textbook_id'), table_name='textbook_chapter')
    op.drop_table('textbook_chapter')
    op.drop_index(op.f('ix_textbook_author_principal_id'), table_name='textbook_author')
    op.drop_table('textbook_author')
    op.drop_table('account_profile')
    op.drop_index(op.f('ix_account_metadata_deleted_at'), table_name='account_metadata')
    op.drop_table('account_metadata')
    op.drop_table('account_identity')
    op.drop_table('account_base_settings')
    op.drop_table('textbook')
    op.drop_table('chapter')
    op.drop_index(op.f('ix_account_status'), table_name='account')
    op.drop_table('account')

    bind = op.get_bind()
    sa.Enum("ACTIVE", "DELETED", "SUSPENDED", name="accountstatus").drop(bind, checkfirst=True)
    sa.Enum("FIREBASE", name="allowedidentityprovider").drop(bind, checkfirst=True)
    sa.Enum("NOT_SET", "JP", "US", name="country").drop(bind, checkfirst=True)
    sa.Enum("DRAFT", "IN_REVIEW", "PUBLISHED", "ARCHIVED", name="textbookstatus").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
