SELECT format(
    'CREATE ROLE %I LOGIN PASSWORD %L',
    :'DB_MIGRATION_USER',
    :'DB_MIGRATION_PASSWORD'
)
WHERE NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = :'DB_MIGRATION_USER'
)\gexec

SELECT format(
    'CREATE ROLE %I LOGIN PASSWORD %L',
    :'DB_APP_USER',
    :'DB_APP_PASSWORD'
)
WHERE NOT EXISTS (
    SELECT 1 FROM pg_roles WHERE rolname = :'DB_APP_USER'
)\gexec

GRANT CONNECT ON DATABASE :"POSTGRES_DB" TO :"DB_MIGRATION_USER", :"DB_APP_USER";
GRANT CREATE ON SCHEMA public TO :"DB_MIGRATION_USER";
GRANT USAGE ON SCHEMA public TO :"DB_APP_USER";

ALTER DEFAULT PRIVILEGES FOR ROLE :"DB_MIGRATION_USER" IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :"DB_APP_USER";
ALTER DEFAULT PRIVILEGES FOR ROLE :"DB_MIGRATION_USER" IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO :"DB_APP_USER";
