#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
    CREATE ROLE "${DB_MIGRATION_USER}" LOGIN PASSWORD '${DB_MIGRATION_PASSWORD}';
    CREATE ROLE "${DB_APP_USER}" LOGIN PASSWORD '${DB_APP_PASSWORD}';

    GRANT CONNECT ON DATABASE "${POSTGRES_DB}" TO "${DB_MIGRATION_USER}", "${DB_APP_USER}";
    GRANT CREATE ON SCHEMA public TO "${DB_MIGRATION_USER}";
    GRANT USAGE ON SCHEMA public TO "${DB_APP_USER}";

    ALTER DEFAULT PRIVILEGES FOR ROLE "${DB_MIGRATION_USER}" IN SCHEMA public
        GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${DB_APP_USER}";
    ALTER DEFAULT PRIVILEGES FOR ROLE "${DB_MIGRATION_USER}" IN SCHEMA public
        GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${DB_APP_USER}";
SQL
