name: before merge ci

on:
  pull_request:
    branches:
      - main

env:
  DB_ADMIN_USER: ${{ secrets.DEV_DB_ADMIN_USER }}
  DB_ADMIN_PASSWORD: ${{ secrets.DEV_DB_ADMIN_PASSWORD }}
  DB_NAME: ${{ secrets.DEV_DB_NAME }}
  DB_MIGRATION_USER: ${{ secrets.DEV_DB_MIGRATION_USER }}
  DB_MIGRATION_PASSWORD: ${{ secrets.DEV_DB_MIGRATION_PASSWORD }}
  DB_APP_USER: ${{ secrets.DEV_DB_APP_USER }}
  DB_APP_PASSWORD: ${{ secrets.DEV_DB_APP_PASSWORD}}
  DB_HOST: "localhost"
  DB_PORT: 5432

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        # Provide the password for postgres
        env:
          POSTGRES_USER: ${{ env.DB_ADMIN_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_ADMIN_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
          DB_MIGRATION_USER: ${{ env.DB_MIGRATION_USER }}
          DB_MIGRATION_PASSWORD: ${{ env.DB_MIGRATION_PASSWORD }}
          DB_APP_USER: ${{ env.DB_APP_USER }}
          DB_APP_PASSWORD: ${{ env.DB_APP_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        volumes:
              - ${{ github.workspace }}/infra/db/init:/docker-entrypoint-initdb.d:ro

    steps:
      - uses: actions/checkout@v6

      - name: install uv
        uses: astral-sh/setup-uv@v8.1.0

      - name: install dependencies
        shell: bash
        run: |-
          set -euo pipefail
          uv sync --locked

      - name: run lint
        shell: bash
        run: uv run ruff check

      - name: run format
        shell: bash
        run: uv run ruff format --check

      - name: run unit test
        shell: bash
        run: |-
          uv run pytest -svv

      - name: migration test
        shell: bash
        run: |-
          uv run alembic upgrade head
          uv run alembic downgrade -1

      - name: setup migration
        shell: bash
        run: |-
          uv run alembic upgrade head
      
      - name: test integration
        shell: bash
        run: |-
          uv run pytest src/test/integration
